###############################################################################
# Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.
###############################################################################

"""Grouped GEMM Benchmark using Triton kernels generated by KernelAgent."""

import argparse
from datetime import datetime

import pandas as pd
import sys

import torch
import torch.utils.benchmark as benchmark
from config import (
    check_allclose,
    check_grouped_gemm_fwd_correctness,
    gen_grouped_gemm_group_lens,
    gen_grouped_gemm_test_cases,
    get_platform_info,
    grouped_gemm_ref,
)
from tabulate import tabulate

# rocm
from optimized_kernel_amd_r10 import kernel_function as kernel_function_r10
from optimized_kernel_amd_r20 import kernel_function as kernel_function_r20

# nvidia
#from optimized_kernel_cuda_r5 import kernel_function as kernel_function_r5
#from optimized_kernel_cuda_r10 import kernel_function as kernel_function_r10
#from optimized_kernel_cuda_r20 import kernel_function as kernel_function_r20

def profile_grouped_gemm(kernelFn, B, M, N, K, dtype):
    device = "cuda"
    x = torch.randn((B * M, K), dtype=dtype, device=device, requires_grad=True)
    w = torch.randn((B, N, K), dtype=dtype, device=device, requires_grad=True)
    group_lens = gen_grouped_gemm_group_lens(B, M, balance=True).to(device)
    offsets = torch.cumsum(group_lens, dim=0, dtype=torch.int32)

    out = kernelFn(x, w.transpose(-2, -1), offsets)
    trans_b = True
    correct = check_grouped_gemm_fwd_correctness(x, w, group_lens, out, dtype, trans_b)

    fwd_func = lambda: kernelFn(x, w.transpose(-2, -1), offsets)

    fwd_total_flops = 2 * B * M * N * K

    for _ in range(30):
        fwd_func()
    torch.cuda.synchronize()

    fwd_timer = benchmark.Timer(stmt="fn()", globals={"fn": fwd_func})
    fwd_measurement = fwd_timer.timeit(100)

    fwd_mean_time_ms = fwd_measurement.mean * 1e3
    fwd_tflops = fwd_total_flops / (fwd_mean_time_ms * 1e-3) / 1e12
    print(f"Forward  Mean time: {fwd_mean_time_ms:.3f} ms | TFLOPS: {fwd_tflops:.2f}")
    return fwd_mean_time_ms, fwd_tflops, correct


def benchmark_grouped_gemm_kernel_agent(kernelFn, output_csv=None):
    platform, gpu_name = get_platform_info()
    test_cases = gen_grouped_gemm_test_cases()
    rows = []
    test_id = 0
    for case in test_cases:
        if test_id == 4:
            break
        test_id += 1
        B = case["B"]
        M = case["M"]
        N = case["N"]
        K = case["K"]
        dtype = case["dtype"]

        print(f"\n{'='*60}")
        print(f"TestID: {test_id}, Case: {case['Case']}, B: {B}, M: {M}, N: {N}, K: {K}, dtype: bf16")
        print(f"{'='*60}")

        try:
            fwd_time_ms, fwd_tflops, correct = profile_grouped_gemm(
                kernelFn=kernelFn, 
                B=B,
                M=M,
                N=N,
                K=K,
                dtype=dtype,
            )
            rows.append(
                {
                    "TestID": test_id,
                    "Platform": platform,
                    "GPU": gpu_name,
                    "Case": case["Case"],
                    "B": B,
                    "M": M,
                    "N": N,
                    "K": K,
                    "Dtype": "bf16",
                    "Check": "PASS" if correct else "FAIL",
                    "Forward Time (ms)": f"{fwd_time_ms:.2f}",
                    "Forward TFLOPS": f"{fwd_tflops:.2f}",
                }
            )

        except Exception as e:
            print(f"Failed to run {case}: {str(e)}")
            rows.append(
                {
                    "TestID": test_id,
                    "Platform": platform,
                    "GPU": gpu_name,
                    "Case": case["Case"],
                    "B": B,
                    "M": M,
                    "N": N,
                    "K": K,
                    "Dtype": "bf16",
                    "Check": "ERROR",
                    "Forward Time (ms)": "ERROR",
                    "Forward TFLOPS": "0.00",
                }
            )

    results = pd.DataFrame(rows)
    print("\nFinal Results:")
    print(tabulate(results, headers="keys", tablefmt="grid", showindex=False))

    avg_fwd_tflops = results["Forward TFLOPS"].astype(float).mean()
    print(f"\nAverage Forward TFLOPS: {avg_fwd_tflops:.2f}")

    if output_csv:
        filename = output_csv
    else:
        timestamp = datetime.now().strftime("%Y%m%d")
        filename = f"grouped_gemm_kernel_agent_benchmark_{timestamp}_{gpu_name}.csv"
    results.to_csv(filename, index=False)
    print(f"Results saved to {filename}")

def grouped_mm_supported_device():
    if torch.cuda.is_available():
        if torch.version.hip:
            supported_architectures = ['gfx94', 'gfx95']
            gcn_arch = torch.cuda.get_device_properties(0).gcnArchName
            return any(arch in gcn_arch for arch in supported_architectures)
        else:
            return torch.cuda.get_device_capability() >= (9, 0) # SM90+
    return False

if __name__ == "__main__":
    if not grouped_mm_supported_device():
        print("Grouped GEMM is only supported on H100+ and sm_89 and MI300+ devices. Skip the benchmark.")
        sys.exit()

    parser = argparse.ArgumentParser(description="Benchmark PyTorch Grouped GEMM (Baseline)")
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default=None,
        help="Output CSV filename. Default: grouped_gemm_kernel_agent_benchmark_{date}_{gpu}.csv",
    )
    args = parser.parse_args()
    for f in [
        #kernel_function_r5,
        kernel_function_r10,
        kernel_function_r20,
    ]:
        benchmark_grouped_gemm_kernel_agent(f, output_csv=args.output)
